//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Application_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStock
    {
        public int StockId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public int StockQty { get; set; }
        public Nullable<System.DateTime> InsertedDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual tblItem tblItem { get; set; }
    }
}
